# Generated by Django 5.1.7 on 2025-06-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_crawl', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=30)),
                ('producers', models.TextField()),
                ('created_date', models.DateField()),
                ('characters', models.ManyToManyField(related_name='movies', to='universe.character')),
                ('planets', models.ManyToManyField(related_name='movies', to='universe.planet')),
            ],
        ),
    ]
